set_property IOSTANDARD LVCMOS33 [get_ports fpga_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports fpga_rst]
set_property IOSTANDARD LVCMOS33 [get_ports start_pg]
set_property PACKAGE_PIN P17 [get_ports fpga_clk]
set_property PACKAGE_PIN N5 [get_ports tx]
set_property PACKAGE_PIN T4 [get_ports rx]
set_property PACKAGE_PIN P15 [get_ports fpga_rst]
set_property PACKAGE_PIN R11 [get_ports start_pg]

set_property IOSTANDARD LVCMOS33 [get_ports {button4[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button4[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button4[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button4[0]}]
set_property PACKAGE_PIN V1 [get_ports {button4[0]}]
set_property PACKAGE_PIN R17 [get_ports {button4[1]}]
set_property PACKAGE_PIN R15 [get_ports {button4[2]}]
set_property PACKAGE_PIN U4 [get_ports {button4[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {switch16[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[8]}]
set_property PACKAGE_PIN P5 [get_ports {switch16[15]}]
set_property PACKAGE_PIN P4 [get_ports {switch16[14]}]
set_property PACKAGE_PIN P3 [get_ports {switch16[13]}]
set_property PACKAGE_PIN P2 [get_ports {switch16[12]}]
set_property PACKAGE_PIN R2 [get_ports {switch16[11]}]
set_property PACKAGE_PIN M4 [get_ports {switch16[10]}]
set_property PACKAGE_PIN N4 [get_ports {switch16[9]}]
set_property PACKAGE_PIN R1 [get_ports {switch16[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {switch16[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch16[0]}]
set_property PACKAGE_PIN U3 [get_ports {switch16[7]}]
set_property PACKAGE_PIN U2 [get_ports {switch16[6]}]
set_property PACKAGE_PIN V2 [get_ports {switch16[5]}]
set_property PACKAGE_PIN V5 [get_ports {switch16[4]}]
set_property PACKAGE_PIN V4 [get_ports {switch16[3]}]
set_property PACKAGE_PIN R3 [get_ports {switch16[2]}]
set_property PACKAGE_PIN T3 [get_ports {switch16[1]}]
set_property PACKAGE_PIN T5 [get_ports {switch16[0]}]

set_property PACKAGE_PIN G2 [get_ports {tub_sel1[3]}]
set_property PACKAGE_PIN C2 [get_ports {tub_sel1[2]}]
set_property PACKAGE_PIN C1 [get_ports {tub_sel1[1]}]
set_property PACKAGE_PIN H1 [get_ports {tub_sel1[0]}]
set_property PACKAGE_PIN B4 [get_ports {tub_control1[7]}]
set_property PACKAGE_PIN A4 [get_ports {tub_control1[6]}]
set_property PACKAGE_PIN A3 [get_ports {tub_control1[5]}]
set_property PACKAGE_PIN B1 [get_ports {tub_control1[4]}]
set_property PACKAGE_PIN A1 [get_ports {tub_control1[3]}]
set_property PACKAGE_PIN B3 [get_ports {tub_control1[2]}]
set_property PACKAGE_PIN B2 [get_ports {tub_control1[1]}]
set_property PACKAGE_PIN D5 [get_ports {tub_control1[0]}]

set_property PACKAGE_PIN G1 [get_ports {tub_sel2[3]}]
set_property PACKAGE_PIN F1 [get_ports {tub_sel2[2]}]
set_property PACKAGE_PIN E1 [get_ports {tub_sel2[1]}]
set_property PACKAGE_PIN G6 [get_ports {tub_sel2[0]}]
set_property PACKAGE_PIN D4 [get_ports {tub_control2[7]}]
set_property PACKAGE_PIN E3 [get_ports {tub_control2[6]}]
set_property PACKAGE_PIN D3 [get_ports {tub_control2[5]}]
set_property PACKAGE_PIN F4 [get_ports {tub_control2[4]}]
set_property PACKAGE_PIN F3 [get_ports {tub_control2[3]}]
set_property PACKAGE_PIN E2 [get_ports {tub_control2[2]}]
set_property PACKAGE_PIN D2 [get_ports {tub_control2[1]}]
set_property PACKAGE_PIN H2 [get_ports {tub_control2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led16[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[8]}]
set_property PACKAGE_PIN F6 [get_ports {led16[15]}]
set_property PACKAGE_PIN G4 [get_ports {led16[14]}]
set_property PACKAGE_PIN G3 [get_ports {led16[13]}]
set_property PACKAGE_PIN J4 [get_ports {led16[12]}]
set_property PACKAGE_PIN H4 [get_ports {led16[11]}]
set_property PACKAGE_PIN J3 [get_ports {led16[10]}]
set_property PACKAGE_PIN J2 [get_ports {led16[9]}]
set_property PACKAGE_PIN K2 [get_ports {led16[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led16[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led16[0]}]
set_property PACKAGE_PIN K1 [get_ports {led16[7]}]
set_property PACKAGE_PIN H6 [get_ports {led16[6]}]
set_property PACKAGE_PIN H5 [get_ports {led16[5]}]
set_property PACKAGE_PIN J5 [get_ports {led16[4]}]
set_property PACKAGE_PIN K6 [get_ports {led16[3]}]
set_property PACKAGE_PIN L1 [get_ports {led16[2]}]
set_property PACKAGE_PIN M1 [get_ports {led16[1]}]
set_property PACKAGE_PIN K3 [get_ports {led16[0]}]



set_property MARK_DEBUG true [get_nets {write_data[3]}]
set_property MARK_DEBUG true [get_nets {write_data[1]}]
set_property MARK_DEBUG true [get_nets {write_data[0]}]
set_property MARK_DEBUG true [get_nets {write_data[4]}]
set_property MARK_DEBUG true [get_nets {write_data[7]}]
set_property MARK_DEBUG true [get_nets {write_data[6]}]
set_property MARK_DEBUG true [get_nets {write_data[2]}]
set_property MARK_DEBUG true [get_nets {write_data[5]}]
set_property MARK_DEBUG true [get_nets {ledout[7]}]
set_property MARK_DEBUG true [get_nets {ledout[15]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list cpuclk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ledout[7]} {ledout[15]}]]
set_property MARK_DEBUG true [get_nets cpuclk]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {write_data[0]} {write_data[1]} {write_data[2]} {write_data[3]} {write_data[4]} {write_data[5]} {write_data[6]} {write_data[7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets cpuclk]
